'use client';

import React from 'react';
import Link from 'next/link';
import { motion } from 'framer-motion';
import { AlertTriangle, ArrowLeft, Gift } from 'lucide-react';
import { Button } from '@/components/ui/button';

export default function Disclaimer() {
  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-50 via-purple-50 to-pink-50 dark:from-slate-950 dark:via-purple-950/20 dark:to-pink-950/20">
      {/* Navigation */}
      <motion.nav
        initial={{ y: -100 }}
        animate={{ y: 0 }}
        className="fixed top-0 left-0 right-0 z-40 bg-white/90 dark:bg-slate-900/90 backdrop-blur-lg shadow-lg"
      >
        <div className="container mx-auto px-4 py-4 flex items-center justify-between">
          <Link href="/" className="flex items-center gap-2">
            <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-purple-500 to-indigo-600 flex items-center justify-center">
              <Gift className="w-5 h-5 text-white" />
            </div>
            <span className="font-bold text-xl dark:text-white">CardGen AI</span>
          </Link>
          
          <Link href="/">
            <Button variant="ghost" className="dark:text-slate-200">
              <ArrowLeft className="w-4 h-4 mr-2" />
              Back to Home
            </Button>
          </Link>
        </div>
      </motion.nav>

      {/* Content */}
      <main className="container mx-auto px-4 py-32 max-w-4xl">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          className="bg-white dark:bg-slate-800 rounded-2xl shadow-xl p-8 md:p-12"
        >
          <div className="flex items-center gap-3 mb-8">
            <div className="w-12 h-12 rounded-xl bg-amber-100 dark:bg-amber-900/30 flex items-center justify-center">
              <AlertTriangle className="w-6 h-6 text-amber-600 dark:text-amber-400" />
            </div>
            <h1 className="text-3xl md:text-4xl font-bold dark:text-white">Disclaimer</h1>
          </div>

          <p className="text-slate-500 dark:text-slate-400 mb-8">
            <strong>Last Updated: January 1, 2026</strong>
          </p>

          <div className="prose prose-slate dark:prose-invert max-w-none space-y-6">
            <section>
              <h2 className="text-xl font-semibold dark:text-white mb-4">General Disclaimer</h2>
              <p className="text-slate-600 dark:text-slate-300 leading-relaxed">
                The information and services provided by CardGen AI are for general informational and entertainment purposes only. While we strive to provide accurate and up-to-date information, we make no representations or warranties of any kind, express or implied, about the completeness, accuracy, reliability, suitability, or availability of the service or the information, products, services, or related graphics contained on the website for any purpose. Any reliance you place on such information is strictly at your own risk.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold dark:text-white mb-4">AI-Generated Content</h2>
              <p className="text-slate-600 dark:text-slate-300 leading-relaxed">
                CardGen AI uses artificial intelligence to generate greeting card messages. The content generated by our AI system may not always be accurate, appropriate, or suitable for your intended purpose. AI-generated content may occasionally include errors, inaccuracies, or content that could be considered offensive or inappropriate by some users. We do not guarantee the quality, accuracy, or appropriateness of any generated content. Users are solely responsible for reviewing, editing, and approving all AI-generated content before sharing or using it.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold dark:text-white mb-4">No Professional Advice</h2>
              <p className="text-slate-600 dark:text-slate-300 leading-relaxed">
                The greeting cards and messages generated by our Service are not intended to constitute professional advice of any kind. This includes but is not limited to legal, medical, financial, or relationship advice. The content is meant for entertainment and personal expression purposes only. If you require professional advice, please consult a qualified professional in the relevant field.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold dark:text-white mb-4">Third-Party Links</h2>
              <p className="text-slate-600 dark:text-slate-300 leading-relaxed">
                Our Service may contain links to third-party websites or services that are not owned or controlled by CardGen AI. We have no control over, and assume no responsibility for, the content, privacy policies, or practices of any third-party websites or services. You acknowledge and agree that CardGen AI shall not be responsible or liable, directly or indirectly, for any damage or loss caused or alleged to be caused by or in connection with the use of or reliance on any such content, goods, or services available on or through any such websites or services.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold dark:text-white mb-4">Limitation of Liability</h2>
              <p className="text-slate-600 dark:text-slate-300 leading-relaxed">
                In no event will CardGen AI be liable for any loss or damage including without limitation, indirect or consequential loss or damage, or any loss or damage whatsoever arising from loss of data or profits arising out of, or in connection with, the use of this Service. Our liability is limited to the maximum extent permitted by applicable law. We are not responsible for any actions taken based on AI-generated content.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold dark:text-white mb-4">Accuracy of Information</h2>
              <p className="text-slate-600 dark:text-slate-300 leading-relaxed">
                We do not warrant that the Service will be uninterrupted, secure, or error-free; that defects will be corrected; that the Service or the servers that make it available are free of viruses or other harmful components; or that the results of using the Service will meet your requirements. The quality of AI-generated content depends on various factors including the input provided by users.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold dark:text-white mb-4">User Responsibility</h2>
              <p className="text-slate-600 dark:text-slate-300 leading-relaxed">
                Users are responsible for ensuring that any content generated through our Service is appropriate for its intended use and audience. This includes reviewing generated content for accuracy, appropriateness, and compliance with applicable laws and regulations. Users should not use or share content that could be considered offensive, harmful, or inappropriate without proper modification.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold dark:text-white mb-4">Indemnification</h2>
              <p className="text-slate-600 dark:text-slate-300 leading-relaxed">
                You agree to indemnify, defend, and hold harmless CardGen AI and its officers, directors, employees, agents, and affiliates from any claim, suit, or action arising from or related to your use of the Service, violation of these terms, or violation of any rights of another. This includes any liability arising from your use or sharing of AI-generated content.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold dark:text-white mb-4">Changes to This Disclaimer</h2>
              <p className="text-slate-600 dark:text-slate-300 leading-relaxed">
                We reserve the right to modify this Disclaimer at any time. Changes will be effective immediately upon posting on the website. Your continued use of the Service after any changes to this Disclaimer constitutes acceptance of those changes. We encourage you to periodically review this Disclaimer for the latest information.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold dark:text-white mb-4">Contact Us</h2>
              <p className="text-slate-600 dark:text-slate-300 leading-relaxed">
                If you have any questions about this Disclaimer, please contact us through our website. We are committed to transparency and are happy to address any concerns you may have about our Service and its limitations.
              </p>
            </section>
          </div>

          {/* Footer Links */}
          <div className="mt-12 pt-8 border-t border-slate-200 dark:border-slate-700">
            <div className="flex flex-wrap items-center justify-center gap-4">
              <Link href="/privacy" className="text-sm text-slate-500 hover:text-purple-600 dark:text-slate-400 dark:hover:text-purple-400 transition-colors">Privacy Policy</Link>
              <span className="text-slate-300 dark:text-slate-600">•</span>
              <Link href="/terms" className="text-sm text-slate-500 hover:text-purple-600 dark:text-slate-400 dark:hover:text-purple-400 transition-colors">Terms of Use</Link>
              <span className="text-slate-300 dark:text-slate-600">•</span>
              <Link href="/disclaimer" className="text-sm text-purple-600 dark:text-purple-400 font-medium">Disclaimer</Link>
              <span className="text-slate-300 dark:text-slate-600">•</span>
              <Link href="/cookies" className="text-sm text-slate-500 hover:text-purple-600 dark:text-slate-400 dark:hover:text-purple-400 transition-colors">Cookies Policy</Link>
            </div>
          </div>
        </motion.div>
      </main>
    </div>
  );
}
