'use client';

import React, { useEffect, useState, useCallback } from 'react';
import { motion } from 'framer-motion';
import {
  AlertTriangle,
  Gift,
  Moon,
  Sun,
  ChevronUp,
  Brain,
  FileWarning,
  CheckCircle,
  XCircle,
  ExternalLink,
  Scale,
} from 'lucide-react';
import { Button } from '@/components/ui/button';
import { cn } from '@/lib/utils';
import Link from 'next/link';

export default function DisclaimerPage() {
  const [isDark, setIsDark] = useState(false);
  const [showScrollTop, setShowScrollTop] = useState(false);

  useEffect(() => {
    // Initialize dark mode from localStorage
    const savedDark = localStorage.getItem('darkMode');
    if (savedDark !== null) {
      const isDarkMode = savedDark === 'true';
      // eslint-disable-next-line react-hooks/set-state-in-effect
      setIsDark(isDarkMode);
      document.documentElement.classList.toggle('dark', isDarkMode);
    } else if (window.matchMedia('(prefers-color-scheme: dark)').matches) {
      setIsDark(true);
      document.documentElement.classList.add('dark');
    }
  }, []);

  useEffect(() => {
    const handleScroll = () => {
      setShowScrollTop(window.scrollY > 300);
    };
    window.addEventListener('scroll', handleScroll);
    return () => window.removeEventListener('scroll', handleScroll);
  }, []);

  const toggleDark = () => {
    setIsDark((prev) => {
      const newValue = !prev;
      document.documentElement.classList.toggle('dark', newValue);
      localStorage.setItem('darkMode', String(newValue));
      return newValue;
    });
  };

  const sections = [
    {
      id: 'general',
      icon: AlertTriangle,
      title: 'General Disclaimer',
      content: `The Greeting Message Generator is provided for entertainment and personal use purposes only. The information and content generated by this service are provided "as is" without any representations or warranties, express or implied.

**No Professional Advice:**
This Service is not intended to provide professional advice of any kind. The greeting card messages generated are for entertainment purposes and should not be relied upon for professional communication, legal matters, medical situations, financial decisions, or any other serious purpose. Always seek appropriate professional advice for important decisions.

**Personal Responsibility:**
Users are solely responsible for how they use the Service and the content generated through it. By using this Service, you acknowledge that you understand its limitations and agree to use it responsibly. We encourage users to review all generated content before sharing it with others.`,
    },
    {
      id: 'ai-content',
      icon: Brain,
      title: 'AI-Generated Content Disclaimer',
      content: `All greeting card messages are generated by artificial intelligence using Groq AI technology. Please be aware of the following important considerations regarding AI-generated content:

**Content Accuracy:**
AI-generated content may not always be factually accurate or appropriate for all situations. The AI may occasionally generate unexpected, unusual, or unintended content. Messages should be carefully reviewed before sharing with recipients. We make no guarantees about the quality, accuracy, or appropriateness of generated content.

**Content Variability:**
The same input may produce different outputs each time due to the nature of AI generation. Generated content is based on patterns learned from training data and may reflect biases present in that data. The AI does not have real-world understanding or consciousness - it generates text based on statistical patterns.

**Review Required:**
We strongly recommend that all users review and edit generated content before sharing. Ensure the message is appropriate for the intended recipient and occasion. Verify any factual information before relying on it. Make any necessary adjustments to better suit your personal needs and the recipient's preferences.`,
    },
    {
      id: 'limitations',
      icon: XCircle,
      title: 'Limitations of Service',
      content: `Users should be aware of the following limitations when using our Service:

**Technical Limitations:**
The Service relies on third-party AI providers and hosting platforms. Service availability depends on these third-party systems. Internet connectivity is required to use the Service. Browser compatibility may affect certain features and functionality. We do not guarantee uninterrupted or error-free operation.

**Content Limitations:**
The AI has knowledge cutoffs and may not be aware of recent events or trends. Language support may vary in quality across different languages. Some specialized or niche topics may not be well-represented in generated content. The AI cannot access real-time information or external databases.

**Usage Limitations:**
The Service is designed for generating greeting card messages, not for other purposes. Bulk or automated usage may be restricted. We reserve the right to limit usage to ensure fair access for all users.`,
    },
    {
      id: 'responsibility',
      icon: Scale,
      title: 'User Responsibility',
      content: `Users of the Service bear the following responsibilities:

**Content Review:**
You are responsible for reviewing all generated content before sharing. You must ensure content is appropriate for the intended recipient and occasion. You should verify any factual claims or information in generated messages. You must edit or modify content as needed to suit your purposes.

**Appropriate Use:**
You must use the Service only for lawful and appropriate purposes. You are responsible for ensuring generated content does not violate any laws or regulations. You must not use the Service to generate harmful, offensive, or illegal content. You are responsible for obtaining any necessary permissions for commercial use of generated content.

**Recipient Consideration:**
Consider the recipient's age, cultural background, and preferences when sharing content. Ensure the content is suitable for the relationship you have with the recipient. Be mindful of the context and timing of sharing greeting card messages.`,
    },
    {
      id: 'third-party',
      icon: ExternalLink,
      title: 'Third-Party Services',
      content: `Our Service utilizes third-party services and technologies. Please note the following:

**AI Provider (Groq AI):**
Greeting card content is generated by Groq AI's language models. Your input is processed by Groq's servers according to their privacy policy and terms of service. We do not control and are not responsible for Groq's data handling practices. You should review Groq's policies to understand how your data is processed.

**Hosting Provider (Vercel):**
The Service is hosted on Vercel's platform. Vercel may collect technical information for security and performance purposes. Their privacy policy governs their data practices and we recommend reviewing it.

**Social Media Platforms:**
When you share cards through social media integration, those platforms apply their own terms and policies. We are not responsible for how third-party platforms handle your shared content. Each platform has its own rules regarding content sharing and user conduct.`,
    },
    {
      id: 'no-guarantee',
      icon: FileWarning,
      title: 'No Warranties or Guarantees',
      content: `We provide no warranties or guarantees regarding the Service. Specifically, we do not guarantee:

**Availability:**
Uninterrupted access to the Service is not guaranteed. Maintenance periods and technical issues may cause temporary unavailability. We may modify or discontinue features without notice.

**Quality:**
We do not guarantee that generated content will meet your expectations or requirements. The quality of AI-generated content may vary significantly. No guarantee is made regarding the accuracy, completeness, or usefulness of generated content.

**Outcomes:**
We do not guarantee any specific results from using the Service. We are not responsible for how recipients respond to your greeting cards. We cannot guarantee that the Service will help you achieve any particular goal or objective.

**Security:**
While we implement security measures, no system is completely secure. We cannot guarantee the security of data transmitted over the internet. You are responsible for protecting your own devices and data.`,
    },
    {
      id: 'liability',
      icon: XCircle,
      title: 'Limitation of Liability',
      content: `To the maximum extent permitted by law, we are not responsible for:

**Direct Damages:**
Any direct damages resulting from your use of the Service. Losses caused by Service unavailability or errors. Damages resulting from reliance on generated content.

**Indirect Damages:**
Indirect, incidental, special, or consequential damages. Loss of profits, data, or business opportunities. Damages resulting from third-party actions or services.

**User Actions:**
How you choose to use generated content. Any offense or harm caused by shared greeting cards. Legal issues arising from your use of the Service. Violations of third-party rights by your use of generated content.

**Maximum Liability:**
Our total liability shall not exceed any amount you have paid for the Service. Since the Service is provided free of charge, our maximum liability is zero. This limitation applies to all claims regardless of the legal theory involved.`,
    },
    {
      id: 'acceptance',
      icon: CheckCircle,
      title: 'Acceptance of Disclaimer',
      content: `By using the Greeting Message Generator Service, you acknowledge and agree that:

**Understanding:**
You have read, understood, and agree to this Disclaimer. You understand the limitations of AI-generated content. You accept that the Service is provided "as is" without warranties. You understand your responsibilities as outlined above.

**Assumption of Risk:**
You voluntarily assume all risks associated with using the Service. You understand that generated content may not always be appropriate or accurate. You accept responsibility for reviewing and verifying all content before use.

**Binding Agreement:**
This Disclaimer forms a binding agreement between you and the Service. If you do not agree with any part of this Disclaimer, you must not use the Service. Your continued use of the Service confirms your acceptance of this Disclaimer.

**Questions:**
If you have questions about this Disclaimer, please contact us through our GitHub repository. We will be happy to clarify any aspects of this Disclaimer. By using the Service, you acknowledge that you have had the opportunity to ask questions and seek clarification.`,
    },
  ];

  return (
    <div className={cn('min-h-screen gradient-bg dark:from-slate-900 dark:via-slate-800 dark:to-slate-900')}>
      {/* Navigation */}
      <nav className="fixed top-0 left-0 right-0 z-40 bg-white/90 dark:bg-slate-900/90 backdrop-blur-lg shadow-lg">
        <div className="container mx-auto px-4 py-4 flex items-center justify-between">
          <Link href="/" className="flex items-center gap-2">
            <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-purple-500 to-indigo-600 flex items-center justify-center">
              <Gift className="w-5 h-5 text-white" />
            </div>
            <span className="font-bold text-xl dark:text-white">CardGen AI</span>
          </Link>
          
          <div className="flex items-center gap-3">
            <Link href="/">
              <Button variant="ghost" size="sm" className="dark:text-slate-200">
                ← Back to App
              </Button>
            </Link>
            <Button
              variant="ghost"
              size="icon"
              onClick={toggleDark}
              className="rounded-full dark:text-slate-200"
              aria-label={isDark ? 'Switch to light mode' : 'Switch to dark mode'}
            >
              {isDark ? <Sun className="w-5 h-5" /> : <Moon className="w-5 h-5" />}
            </Button>
          </div>
        </div>
      </nav>

      {/* Scroll to Top */}
      {showScrollTop && (
        <button
          onClick={() => window.scrollTo({ top: 0, behavior: 'smooth' })}
          className="fixed bottom-6 right-6 z-40 w-12 h-12 rounded-full bg-gradient-to-br from-purple-500 to-indigo-600 text-white shadow-lg flex items-center justify-center hover:scale-110 transition-transform"
          aria-label="Scroll to top"
        >
          <ChevronUp className="w-6 h-6" />
        </button>
      )}

      {/* Hero Section */}
      <section className="pt-24 pb-12">
        <div className="container mx-auto px-4">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6 }}
            className="text-center max-w-3xl mx-auto"
          >
            <div className="w-16 h-16 mx-auto mb-6 rounded-2xl bg-gradient-to-br from-amber-500 to-orange-600 flex items-center justify-center">
              <AlertTriangle className="w-8 h-8 text-white" />
            </div>
            <h1 className="text-4xl md:text-5xl font-bold mb-4 dark:text-white">
              Disclaimer
            </h1>
            <p className="text-slate-600 dark:text-slate-300 text-lg">
              Important information about using our AI-powered greeting card generator service.
            </p>
            <p className="text-sm text-slate-500 dark:text-slate-400 mt-4">
              Last updated: January 1, 2026
            </p>
          </motion.div>
        </div>
      </section>

      {/* Table of Contents */}
      <section className="pb-8">
        <div className="container mx-auto px-4">
          <div className="max-w-4xl mx-auto">
            <div className="bg-white dark:bg-slate-800 rounded-2xl shadow-lg p-6 border border-slate-200 dark:border-slate-700">
              <h2 className="text-lg font-semibold mb-4 dark:text-white">Table of Contents</h2>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-2">
                {sections.map((section) => (
                  <a
                    key={section.id}
                    href={`#${section.id}`}
                    className="flex items-center gap-2 text-slate-600 dark:text-slate-300 hover:text-purple-600 dark:hover:text-purple-400 transition-colors py-1"
                  >
                    <section.icon className="w-4 h-4" />
                    {section.title}
                  </a>
                ))}
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Content Sections */}
      <section className="pb-16">
        <div className="container mx-auto px-4">
          <div className="max-w-4xl mx-auto space-y-8">
            {sections.map((section, index) => (
              <motion.div
                key={section.id}
                id={section.id}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ duration: 0.6, delay: index * 0.1 }}
                className="bg-white dark:bg-slate-800 rounded-2xl shadow-lg p-8 border border-slate-200 dark:border-slate-700"
              >
                <div className="flex items-center gap-3 mb-6">
                  <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-purple-500 to-indigo-600 flex items-center justify-center">
                    <section.icon className="w-5 h-5 text-white" />
                  </div>
                  <h2 className="text-2xl font-bold dark:text-white">{section.title}</h2>
                </div>
                <div className="prose prose-slate dark:prose-invert max-w-none">
                  {section.content.split('\n\n').map((paragraph, i) => (
                    <p key={i} className="text-slate-600 dark:text-slate-300 mb-4 leading-relaxed">
                      {paragraph.split('\n').map((line, j) => (
                        <span key={j}>
                          {line.startsWith('**') && line.endsWith('**') ? (
                            <strong className="dark:text-white">{line.replace(/\*\*/g, '')}</strong>
                          ) : (
                            line
                          )}
                          {j < paragraph.split('\n').length - 1 && <br />}
                        </span>
                      ))}
                    </p>
                  ))}
                </div>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* Footer */}
      <footer className="py-8 bg-slate-50 dark:bg-slate-800 border-t dark:border-slate-700">
        <div className="container mx-auto px-4 text-center">
          <div className="flex flex-wrap items-center justify-center gap-4 mb-4">
            <Link href="/privacy" className="text-sm text-slate-500 dark:text-slate-400 hover:text-purple-600 dark:hover:text-purple-400 transition-colors">
              Privacy Policy
            </Link>
            <span className="text-slate-300 dark:text-slate-600">•</span>
            <Link href="/terms" className="text-sm text-slate-500 dark:text-slate-400 hover:text-purple-600 dark:hover:text-purple-400 transition-colors">
              Terms of Use
            </Link>
            <span className="text-slate-300 dark:text-slate-600">•</span>
            <Link href="/disclaimer" className="text-sm text-purple-600 dark:text-purple-400 font-medium">
              Disclaimer
            </Link>
            <span className="text-slate-300 dark:text-slate-600">•</span>
            <Link href="/cookies" className="text-sm text-slate-500 dark:text-slate-400 hover:text-purple-600 dark:hover:text-purple-400 transition-colors">
              Cookies Policy
            </Link>
          </div>
          <p className="text-slate-400 dark:text-slate-500 text-xs">
            © 2026 CardGen AI. All rights reserved.
          </p>
        </div>
      </footer>
    </div>
  );
}
